version: '3'

services:
    upload-service:
        build: 
        volumes: 
            - ../songs:/var/songs
        ports: 
            - 3000:3000
    streaming-service:
        build: 
        volumes: 
            - ../songs:/var/songs
        ports: 
            - 3001:3000
    download-service:
        build: 
        volumes: 
            - ../songs:/var/songs
        ports: 
            - 3002:3000
    metadata-service:
        build: 
        ports: 
            - 3004:3000
    users-service:
        build: 
        ports: 
            - 3005:3000
    express-gateway:
        build: 
        ports: 
            - 80:8081