http:
  port: 8081
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  upload:
    paths:
      - '/uploadsong'
  download:
    paths:
      - '/getSongDownload'
  metadata:
    paths:
      - '/songs/createSong'
      - '/songs/getSong'
      - '/songs/createArtist'
      - '/songs/getArtist'
      - '/songs/createAlbum'
      - '/songs/getAlbum'
  users:
    paths:
      - '/login'
      - '/create'
      - '/tokenAuthorization'


  # This has to be last always
  streaming:
    paths: '*'

serviceEndpoints:
  uploadService:
    url: 'http://upload-service:3000'
  streamingService:
    url: 'http://streaming-service:3001'
  downloadService:
    url: 'http://download-service:3002'
  listService:
    url: 'http://localhost:3003'
  metadataService:
    url: 'http://metadata-service:3004'
  usersService:
    url: 'http://users-service:3005'
  libraryService:
    url: 'http://localhost:3006'
  imageService:
    url: 'http://localhost:3007'
policies:
  - cors
  - expression
  - log
  - proxy
  - rate-limit
pipelines:
  upload:
    apiEndpoints:
      - upload
    policies:
      - proxy:
          - action:
              serviceEndpoint: uploadService 
              changeOrigin: true
  streaming:
    apiEndpoints:
      - streaming
    policies:
      - proxy:
          - action:
              serviceEndpoint: streamingService 
              changeOrigin: true
  download:
    apiEndpoints:
      - download
    policies:
      - proxy:
          - action:
              serviceEndpoint: downloadService
              changeOrigin: true
  metadata:
    apiEndpoints:
      - metadata
    policies:
      - proxy:
          - action:
              serviceEndpoint: metadataService
              changeOrigin: true
  users:
    apiEndpoints:
      - users
    policies:
      - proxy:
          - action:
              serviceEndpoint: usersService
              changeOrigin: true