http:
  port: 8081
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: 
      - '/ip' 
      - '/get'
  upload:
    host: localhost
    paths:
      - '/uploadsong'
  streaming:
    host: localhost

serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  uploadService:
    url: 'http://localhost:3001'
  streamingService:
    url: 'http://localhost:3000'
policies:
  - expression
  - log
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
  upload:
    apiEndpoints:
      - upload
    policies:
      - proxy:
          - action:
              serviceEndpoint: uploadService 
              changeOrigin: true
  streaming:
    apiEndpoints:
      - streaming
    policies:
      - proxy:
          - action:
              serviceEndpoint: streamingService 
              changeOrigin: true


